### ISSUE TITLE
Bug when saving translation that are inside other folders

### ISSUE THREAD

**Issue by salomonsanz** [joedixon/laravel-translation#66] opened 2019-04-29 06:10 UTC
**Describe the bug**
Sometimes, to organize the translation resources, is necesary to group them into a subfolder like this:
![image](https://user-images.githubusercontent.com/24811202/56878547-f020f680-6a54-11e9-98cd-71e5155f0462.png)

These files are detected ok, but when saving, doesn't save in the same place, instead, it is saved one level up and duplicates the original one.
![image](https://user-images.githubusercontent.com/24811202/56878780-1abf7f00-6a56-11e9-9bfd-6ba05b73610f.png)

Also, i think, would be util improve the interface adding the path like this:
![image](https://user-images.githubusercontent.com/24811202/56878651-72a9b600-6a55-11e9-88b7-97ab81ba3ded.png)
![image](https://user-images.githubusercontent.com/24811202/56878671-8bb26700-6a55-11e9-9c2c-0e2ed9ddcab2.png)

**To Reproduce**
1. Create a translation file into a subfolder: lang_folder->subfolder->translationfile.php
2. Save a translation of this file using the UI

**Expected behavior**
The changes should be saved in the same file

**Comment by stefnats** [comment] 2019-04-29 14:09
Duplicate of #56 which was closed and not resolved.

**Comment by salomonsanz** [comment] 2019-04-29 14:28
ups sorry, i didn't see it

**Comment by joedixon** [comment] 2019-06-23 12:47
I would like this functionality, but I'm not in a position to be able to add it right now.

I'd be open to a PR if you're interested?

**Closed by joedixon** 2019-06-23 12:47 UTC

**Comment by mruz** [comment] 2019-07-23 17:08
It's not resolved bug, so it shouldn't be closed.

**Comment by joedixon** [comment] 2019-07-23 20:07
It's not a bug, there is no support for nested translations and I don't plan to add it right now.

**Comment by mruz** [comment] 2019-07-23 21:23
For me if it doesn't support default laravel's behaviour:
```php
trans('accounts/tickets.key');
```
it's a bug :smile: 
![Bug/Feature](http://i.imgur.com/TQovrwC.jpg)

Please reopen, maybe someone will fix it.
